+++
title = '테스트 작성'
date = 2024-05-07T00:20:22+09:00
draft = true
+++
## Test

### jest.fn() vs jest.spyOn()

jest.fn은 가짜 함수를 생성한다.
mockFn.mockReturnValue(리턴값) 
mockFn.mockResolvedValue(리턴값) -> 가짜 비동기 함수
mockImplementation(구현코드)

```typescript
authContextService.getUserId = jest
	.fn()
	.mockImplementationOnce(() => {
		throw new HttpException(UNAUTHORIZED, 401);
	});
```
- mock 함수를 만들고 그것의 구현을 직접 삽입.
만약 () => {} 익명함수가 아닌 그냥 new HttpException을 하면 당연히 안됨.
함수인데 에러객체를 넣어버리는거니까..

jest.spyOn()은 함수 구현을 가짜로 대체하지 않고,
특정 객체의 메서드에 spy를 붙여놓고
그 메서드를 실행하면 
실제 spy가 불렸는지 알 수 있다. 

내가 보려는 함수는 video이고 거기서 play가 불렸는지 알고싶을때.
```typescript
const spy = jest.spyOn(video, 'play');
const result = video.play();

expect(spy).toHaveBeenCalled();
```

### 두 가지 방식 비교
무엇이 나은가?
어느쪽이든간에 특정 결과를 리턴하게 하려면 `mockImplementation`을 써야한다.
왜 `mockImplementation`을 쓰는가?
저렇게 테스트 코드를 작성하지 않으면, authContext 에서 구현이 변경될 경우 해당 테스트에 영향을 끼치기 때문에 영향 받지 않도록 mock 객체로 대체하는 것이다.
- 그것이 `mockImplementation`로 해당 함수를 통째로 재구현하는 것이든,
- mockReturnValue로 반환값을 정의하는 것이든.


의도는 실제 authContextService의 getUserId 함수가 작동하는지 알려는 게 아니라(이건 범위가 아님)
getUserId가 401 에러를 던졌을 때 호출함수에서도 401을 반환하냐는 것.
그러나.. mockImplementation으로 이미 특정 에러를 반환하도록 아예 대체해버리면
그걸 반환하는건 너무 당연한건데 테스트의 의미가?


```typescript
// jest.fn() -> 가짜 함수로 대체
it('userId가 없으면 401 UNAUTHORIZED 에러가 발생한다', async () => {
	// Given
	authContextService.getUserId = jest
		.fn()
		.mockImplementationOnce(() => {
			throw new HttpException(UNAUTHORIZED, 401);
		});
	// Then
	await expect(
		groupUseCase.create(mockGroupCreateDto),
	).rejects.toThrowError(new HttpException(UNAUTHORIZED, 401));
});

// jest.spyOn -> 특정 메서드에 spy 달기
it('userId가 없으면 401 UNAUTHORIZED 에러가 발생한다', async () => {
	// Given
	const getContextUserIdSpy = jest
		.spyOn(authContextService, 'getUserId')
		.mockImplementation(() => {
			throw new HttpException(UNAUTHORIZED, 401);
		});
	// Then
	await expect(
		groupUseCase.create(mockGroupCreateDto),
	).rejects.toThrowError(new HttpException(UNAUTHORIZED, 401));

	expect(getContextUserIdSpy).toBeCalledTimes(1);
});
```




---
저장/업데이트 유스케이스 테스트
- spyOn으로 하는 케이스.
- 에러 케이스는 save 자체의 실패보다는, .save의 mockResolvedValue가 
null 또는 [] 빈배열 등 미리 정의한 케이스에 따라
expect toThrowError 하도록 하는 것.
- save 결과를 가지고 정상여부를 판단하는게 나쁘지 않은듯. 무조건 throw error보다.

```typescript
it('contract status 업데이트 후 저장에 실패할 경우, 에러를 반환한다.', async () => {
	const findByDocumentIdSpy = jest
		.spyOn(contractRepository, 'findByDocumentId')
		.mockResolvedValue(mockContract as any);

	const changeStatusByWebhhokTypeSpy = jest.spyOn(
		mockContract,
		'changeStatusByWebhhokType',
	);

	const saveSpy = jest
		.spyOn(contractRepository, 'save')
		.mockResolvedValue(null);

	await expect(
		contractService.updateContractStatus(mockContractWehhookDto),
	).rejects.toThrowError('FAILED_CONTRACT_STATUS_CHANGE');
	expect(findByDocumentIdSpy).toBeCalledTimes(1);
	expect(changeStatusByWebhhokTypeSpy).toBeCalledTimes(1);
	expect(saveSpy).toBeCalledTimes(1);
});

it('contract status 업데이트 후 저장에 성공한다.', async () => {
	const findByDocumentIdSpy = jest
		.spyOn(contractRepository, 'findByDocumentId')
		.mockResolvedValue(mockContract as any);

	const changeStatusByWebhhokTypeSpy = jest.spyOn(
		mockContract,
		'changeStatusByWebhhokType',
	);

	const saveSpy = jest
		.spyOn(contractRepository, 'save')
		.mockResolvedValue({} as any);

	const result = await contractService.updateContractStatus(
		mockContractWehhookDto,
	);

	expect(result).toEqual(true);
	expect(findByDocumentIdSpy).toBeCalledTimes(1);
	expect(changeStatusByWebhhokTypeSpy).toBeCalledTimes(1);
	expect(saveSpy).toBeCalledTimes(1);
});
});
```